# Generated by Django 3.1.7 on 2021-03-13 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая стоимость')),
                ('current_shop', models.CharField(default='', max_length=127, verbose_name='Текущий магазин')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, unique=True, verbose_name='Название магазина')),
                ('address', models.CharField(max_length=127, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('category_choicer', models.CharField(choices=[('grocery', 'Продуктовый магазин'), ('restaurant', 'Ресторан'), ('clothes', 'Магазин одежды'), ('furniture', 'Магазин мебели'), ('electronics', 'Магазин электроники')], max_length=15, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата покупки')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма, потраченная на товар')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Наименование товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('moderated', models.BooleanField(default=False, verbose_name='Готов к продаже')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='CheckProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Наименование')),
                ('product_pk', models.IntegerField(verbose_name='Артикул продукта')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('shop_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shopcheck', verbose_name='Чек')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cart', verbose_name='Корзина')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='Сам продукт')),
            ],
        ),
    ]
