version: '3.7'

services:
  purchase:
    build: ./purchase
    command: sh -c " gunicorn --bind 0.0.0.0:8001 purchase.wsgi"
    expose:
      - 8001

  shop:
    build: ./shop
    command: sh -c " gunicorn --bind 0.0.0.0:8002 shop.wsgi"
    expose:
      - 8002

  factory:
    build: ./factory
    command: sh -c "python3 manage.py collectstatic --noinput &&  gunicorn --bind 0.0.0.0:8003 factory.wsgi && python3 pycron.py"
    volumes:
      - static:/usr/src/factory/static
      - /home/bojan/kek/mirea_rtuitlab/project/factory
    expose:
      - 8003


  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/usr/src/factory/static
      - /home/bojan/kek/mirea_rtuitlab/project/factory
    depends_on:
      - shop
      - purchase
      - factory

volumes:
  static: