version: '3.7'

services:
  purchase:
    build: ./purchase
    command: sh -c "python3 manage.py runserver 0.0.0.0:8001"
    expose:
      - 8001
    ports:
      - "8001:8001"
  shop:
    build: ./shop
    command: sh -c "python3 manage.py runserver 0.0.0.0:8002"
    expose:
      - 8002
    ports:
      - "8002:8002"
  factory:
    build: ./factory
    command: sh -c "python3 manage.py runserver 0.0.0.0:8003"
    expose:
      - 8003
    ports:
      - "8003:8003"

