# Generated by Django 3.1.7 on 2021-03-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название завода')),
                ('productivity_coefficient', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Коэффициент производительность')),
                ('available', models.PositiveIntegerField(verbose_name='Свободный товар')),
                ('category_choicer', models.CharField(choices=[('grocery', 'Продуктовый завод'), ('restaurant', 'Ресторанный завод'), ('clothes', 'Завод одежды'), ('furniture', 'Завод мебели'), ('electronics', 'Завод электроники')], max_length=15, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название продукта')),
            ],
        ),
        migrations.CreateModel(
            name='ShopTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название магазина')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('queue', models.PositiveIntegerField(default=1, verbose_name='Количество неотправленных поставок')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.factory', verbose_name='Завод')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='Продукт')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shoptitle', verbose_name='Магазин')),
            ],
        ),
    ]
