# Generated by Django 3.1.7 on 2021-03-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='available',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Свободный товар'),
        ),
    ]
