# Generated by Django 3.1.7 on 2021-03-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Стандартная категория'),
        ),
    ]
