# Generated by Django 3.1.7 on 2021-03-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_category_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.purchase', verbose_name='Покупка'),
        ),
    ]
