# Generated by Django 3.1.7 on 2021-03-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210306_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='product_pk',
            field=models.PositiveIntegerField(verbose_name='Артикул продукта'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
